### ISSUE TITLE
Drag and drop does not work at 1024*768 resolution

### ISSUE THREAD

**Issue by indikaanu83** [DigitalWheat/Email-Builder#2]
Hi,
I tried with Chrome developer tools. I set it up to 1024*768 resolution and the drag n drop stopped working. Any idea on this?

**Comment by maxkostinevich** [comment]
It may not work properly in Chrome developers tools, please, test on real device.

**Comment by indikaanu83** [comment]
yes. you are correct. It works.

Thanks
